package desktopview.view;

public enum SubViewType {

    EVALUTIONSUBVIEW,
    APPLICANTSKILLSUBVIEW,
    NEWJOBORDERSUBVIEW,
    UPDATEJOBORDERSUBVIEW,
    ADDNEWADMINSUBVIEW,
    ADDNEWINTERVIEWSUBVIEW,
    SETTINGSSUBVIEW,
    TOOLSSUBVIEW,
    MYACCOUNTSUBVIEW,
    APPLICANTHOMESUBVIEW,
    EMPLOYERCONTACTHOMESUBVIEW,
    ADMINHOMESUBVIEW

}
